[2017-02-07 18:25:08 +0000] [7046] [INFO] Starting gunicorn 19.6.0
[2017-02-07 18:25:08 +0000] [7046] [INFO] Listening at: http://0.0.0.0:5000 (7046)
[2017-02-07 18:25:08 +0000] [7046] [INFO] Using worker: sync
[2017-02-07 18:25:08 +0000] [7049] [INFO] Booting worker with pid: 7049
[2017-02-07 18:25:24,577] ERROR in app: Exception on /ec2_examples [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/Desktop/ece1779/aws/app/ec2_examples.py", line 22, in ec2_list
    return render_template("ec2_examples/list.html",title="EC2 Instances",instances=instances)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/Desktop/ece1779/aws/app/templates/ec2_examples/list.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ubuntu/Desktop/ece1779/aws/app/templates/base.html", line 11, in top-level template code
    {% block content %}
  File "/home/ubuntu/Desktop/ece1779/aws/app/templates/ec2_examples/list.html", line 15, in block "content"
    {% for instance in instances %}
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/botocore/paginate.py", line 102, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/botocore/paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/Desktop/ece1779/databases/venv/lib/python3.5/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials
[2017-02-07 18:25:27 +0000] [7046] [INFO] Handling signal: int
[2017-02-07 18:25:27 +0000] [7049] [INFO] Worker exiting (pid: 7049)
[2017-02-07 18:25:28 +0000] [7046] [INFO] Shutting down: Master
